name: Worldbridger Wellness
favicon: null
layout_spectrum: 0.8298857335466892
typography_spectrum: 0.4525465948972851
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5892046485096216
  lightness: 0.6304278033785522
  saturation: 0.7717464473098516
  rhythmicContrast: 0.24976039328612387
purpose: []
